### ISSUE TITLE
Generated 0 resources

### ISSUE THREAD

**Issue by waldner** [upbound/upjet#140]
### What happened?

Trying to generate a provider based on https://registry.terraform.io/providers/vmware/vcd/3.7.0. Following the guide at https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md, here's the relevant `Makefile` section, which looks correct to me:

```
export TERRAFORM_PROVIDER_SOURCE := vmware/vcd
export TERRAFORM_PROVIDER_REPO := https://github.com/vmware/terraform-provider-vcd
export TERRAFORM_PROVIDER_VERSION := 3.7.0
export TERRAFORM_PROVIDER_DOWNLOAD_NAME := terraform-provider-vcd
export TERRAFORM_NATIVE_PROVIDER_BINARY := terraform-provider-vcd_v3.7.0
export TERRAFORM_DOCS_PATH := website/docs/r
```

I customized `internal/clients/vcd.go` with the configuration keys as follows:

```
                ps.Configuration = map[string]any{
                        "user":     creds["user"],
                        "password": creds["password"],
                        "org":      creds["org"],
                        "url":      creds["url"],
                }

                // optional values
                for _, n := range []string{"vdc", "auth_type", "allow_unverified_ssl", "max_retry_timeout"} {
                        if v, ok := creds[n]; ok {
                                ps.Configuration[n] = v
                        }
                }

                return ps, nil

```

I want to generate all resources, to I just ran: `make generate`.
While no error is produced, no resource is generated, either, see the attached logfile.

I was able to do the same thing above with terrajet, so perhaps I'm missing something obvious here. Thanks.

[log.txt](https://github.com/upbound/upjet/files/10014673/log.txt)

**Comment by ulucinar** [comment]
Hi @valdner, 
I believe it's expected that no resources are generated because my understanding is that you still need to supply external-name configurations for your managed resources to be generated [here](https://github.com/upbound/upjet-provider-template/blob/05c03f0f6ab6d1c2083098f6516651b55bbae648/config/external_name.go#L11).

Upjet has the notion of a provider configuration, which you can provide via the [provider configuration API](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/provider.go#L51). In that API, we have the [config.Provider.IncludeList](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/provider.go#L99) that specifies a list of regular expressions. If a Terraform resource from the Terraform provider's schema matches any regex from this list, then we attempt to generate a corresponding Crossplane managed resource. And if you provide an external-name configuration for a Terraform resource via [config. ExternalNameConfigs](https://github.com/upbound/upjet-provider-template/blob/05c03f0f6ab6d1c2083098f6516651b55bbae648/config/external_name.go#L11), then it's included and a corresponding managed resource is generated.

**Comment by waldner** [comment]
Hi @ulucinar ,

thanks for your reply. It turns out that, coming from terrajet, my understanding of external-name was wrong. I now see that resources do get generated when I add `ExternalNameConfigs`.
Thanks!

**Comment by ulucinar** [comment]
Hi @waldner,
It's my pleasure! Yes, it's possible to specify a default configuration for your resources. But even if you do so, you will still need to specify the `IncludeList`. For example, in `upbound/provider-aws`, we are utilizing the `config.ExternalNameconfigs` map to [populate the `IncludeList`](https://github.com/upbound/provider-aws/blob/99125df2128ee943930f43fe04506059c410bf80/config/provider.go#L121).

However, you do not need to know and specify each Terraform resource's name at compile time. [config.Provider.IncludeList](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/provider.go#L99) expects an array of regular expressions, so something like the following in your [config.GetProvider](https://github.com/upbound/upjet-provider-template/blob/05c03f0f6ab6d1c2083098f6516651b55bbae648/config/provider.go#L28) function should do the job:
```go
	pc := config.NewProvider([]byte(providerSchema), resourcePrefix, modulePath, []byte(providerMetadata),
		config.WithIncludeList([]string{`.*`}),
...
```

And if you need to skip generation of any resources (for example, you may hit some bugs), then you can specify a `SkipList` with the [config.WithSkipList](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/provider.go#L145), which again expects an array of regular expressions. 

And in order to define a default resource configuration, you can use the [config.WithDefaultResourceOptions](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/provider.go#L160), though which you can configure the default [resource configuration options](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/common.go#L37) to be applied to all generated resources.

**Comment by waldner** [comment]
Hi @ulucinar,

many thanks! I just have another question...the autogenerated code in `provider.go` does this:

```
func GetProvider() *ujconfig.Provider {
        pc := ujconfig.NewProvider([]byte(providerSchema), resourcePrefix, modulePath, []byte(providerMetadata),
                ujconfig.WithIncludeList(ExternalNameConfigured()),       // <<--------------
                ujconfig.WithDefaultResourceOptions(
                        ExternalNameConfigurations(),
                ))
...
```
(comment is mine) where, as you said, `ExternalNameConfigured()` explicitly includes all resources declared in the `ExternalNameConfigs` in `external_name.go`. But then, it looks to me that by default, the include list is already `.+` (see https://github.com/upbound/upjet/blob/main/pkg/config/provider.go#L206), so to include all resources I could just remove the marked `ujconfig.WithIncludeList(ExternalNameConfigured())` call in `provider.go`, right? Is my understanding correct?

**Comment by ulucinar** [comment]
Hi @waldner,
Thank you for checking it. As you mentioned, we still generally need custom (resource) configuration for the resources being generated (at least the external name configuration). Our [resource configuration guide](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md) gives an overview of the configuration process, and [here](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md) you can find a more detailed account. 

Upjet provides a default configuration for all the generated resources but sometimes with that default configuration, a generated managed resource may not be functioning. And at some other times, we would like to have higher levels of conformance to the [Crossplane resource model](https://crossplane.io/docs/v1.10/concepts/terminology.html#crossplane-resource-model) (e.g., managed resource API normalization, cross resource references, etc.) and thus, we do some custom configuration.
