### ISSUE TITLE
No rule to make target 'generate'

### ISSUE THREAD

**Issue by optik-aper** [upbound/upjet#199]
### What happened?

I am not able to run `make generate` on a newly configured provider.  After follwing the steps in the guide, I run into this when trying to:

``` sh
make: *** No rule to make target 'generate'.  Stop.
```

### How can we reproduce it?

- Clone my [repo](https://github.com/optik-aper/crossplane-provider-vultr) which should be ready to generate
- Try to generate

I'm not sure if this is a system issue or missing packages or something.  I attempting this on Ubuntu 22.04

**Comment by optik-aper** [comment]
This appears to be an issue with missing the `build` submodule because it works when building directly from the template.  I think it might be something in the template from the crossplane-contrib repo.

**Comment by optik-aper** [comment]
@ytsarev I tried that.  Running only `make` threw an error because of missing build files.  Though `make submodules` did succeed, it did not add the build directory.

**Comment by bobh66** [comment]
The upjet-provider-template Makefile had the default target setup incorrectly, which was fixed by https://github.com/upbound/upjet-provider-template/pull/33 - the `fallthrough:` target in the Makefile needs to be the first one.  That allows the `make` command to automatically trigger `make submodules` which populates the build submodule.

**Comment by optik-aper** [comment]
@bobh66 That makes sense.  Thanks for the update.
